### ISSUE TITLE
Error, no message

### ISSUE THREAD

**Issue by mnakalay** [leafo/scssphp#358]
Hello,

I am using scssphp on a project where I get variable values from mysql than concatenate that with my scss file and send it to scssphp.

It works just fine on my system and others but it absolutely refuse to work on a friend's system and just fails without an error message.

We are under the impression that it is due to a loop somewhere going nuts but can't figure it out especially since it works on some machines and not others.

The machine on which it's not working is winxp with php 5.3.29.

Then we tried it differently, I added the variables directly in the scss file and it worked in one scenario but not another.

What happens is it's part of a plugin for a CMS. The css generation is run during the install routine fo the plugin and later it can be run manually from the dashboard.

After adding the variables direclty in the scss file, the manual generation started working but the one during install kept failing without a message. Just a 500.

BUT, adding a simple line to log the content of the file after calling the compiler makes even the manual call fail.

It is not a timeout as it fails in just a few second (between 5 and 10) and allowed execution time is up to 30 seconds.

One thing we noticed is that if we comment out one of the @import in the scss, it also will work during manual generation.

On my system, it never fails (win 7 64 with php 5.4.x)

I understand that's not much to work with but have you come across anything like this before? Any idea what could be doing it?

**Comment by robocoder** [comment]
Sorry, I need a test case to troubleshoot.

Also, you haven't specified what version of scssphp you're using but I recommend you use the latest version as there are many compatibility and bug fixes (e.g., @import loop detection).

**Comment by mnakalay** [comment]
Hello, I am using the latest downloaded yesterday from github.

As I said, it works just fine on my computer but not at all on a friend's so I'm not sure how to provide a test case

**Comment by robocoder** [comment]
Since it fails quickly rather than timing out, I don't think it's stuck in a loop.

Try checking your friend's php configuration, i.e., call php_info() before the scssphp run. Memory limit is a common problem.

http://php.net/manual/en/ini.core.php#ini.memory-limit

Other possibilities are safe mode and open basedir.

Another thing to try is log the actual results of the query when fetching the variables from mysql, to make sure it's not being escaped in some way.

Happy troubleshooting.

**Comment by mnakalay** [comment]
Hey thank you for your answer. Memory is not the problem, he has 128Mo just like me.
I checked the variables and they were not escaped (and worked on my system)

I'll check for safe mode and open basedir, thank you.

**Comment by mnakalay** [comment]
For both of us safe mode is disabled and open basedir has no value. So I guess that's not the problem

**Comment by robocoder** [comment]
I don't have a 5.3.x WAMP test environment but if you can send me the scss, I can take a look.

Otherwise, try instrumenting Compiler.php and Parser.php with calls to `file_put_contents('/pathToLogFile', __FILE__.':'.__LINE__."\n", FILE_APPEND);`

This may allow you to follow the execution and figure out where it's stuck/failing.

**Comment by mnakalay** [comment]
thank you. The scss is a buttons library you can find here: http://unicorn-ui.com/buttons/

You will see the library uses maps for colors, sizes, shapes...

In my code those maps are generated server side as strings and then concatenated to the scss file's content and sent le scssphp.

I am not using quotation marks around the values. For instance:

"$ubtn-shapes: (primary: #1B9AF7  #FFF, plain: #FFF #1B9AF7);"

To be honest, I just went on and converted the whole thing to LESS and I am now using your LESS processor and everything is working fine, no more problem.
