### ISSUE TITLE
PHP Fatal error sometimes

### ISSUE THREAD

**Issue by Toccamonium** [leafo/scssphp#512]
Hi, 
Sometimes I get an time-out which ends with this error on Contao 3.5.27 >
PHP Fatal error:  Maximum execution time of 90 seconds exceeded in /html/contao-2017/vendor/leafo/scssphp/src/Compiler.php on line 1162

Any idea what could cause this? Because within this time I didn't change any SCSS and no upload happended for this file. Is there a methode to debug it more closely?

thx
Florian

**Comment by mahagr** [comment]
You need faster server.

**Comment by vita10gy** [comment]
You're likely always pushing 90 seconds and sometimes enough other things are going on to push it over and sometimes not. 

You can up that 90 second setting a few ways, just google "PHP Fatal error: Maximum execution time".

A 90 second build is an eternity though.

**Comment by mahagr** [comment]
@Toccamonium I am sorry from my fast response, I was merely tagging the message as I was really busy yesterday.

SCSS compilation takes a long time as there is a lot of processing to do. For that, you need a fast server, which can cut the response time to few seconds. It doesn't mean that the server has to be expensive as $10-$20 / month vps can easily do it if you pick a good provider.

**Comment by robocoder** [comment]
I'm closing this issue because it doesn't identify a specific issue with the `scssphp` library. Performance is a general consideration and invariably there are tradeoffs with maintainability.

You mention you "didn't change any SCSS and no upload happended for this file". This sounds like Contao doesn't examine timestamps and/or cache the generated stylesheet to see if recompilation is necessary. That would be something to follow-up with the Contao developers.

You can also see if it's possible to increase php's `max_execution_time` on your server or precompiling your scss, so Contao serves up static stylesheets.

**Comment by Toccamonium** [comment]
Thanks for your hints!
