### ISSUE TITLE
Wrong CSS result

### ISSUE THREAD

**Issue by informas** [leafo/scssphp#530]
I'm trying to recompile .scss file containing some pieces of code like this:
```
@mixin make-hidden-responsive ($hidden-prefix : 'hidden', $hidden-medium-breakpoint : 768px,
  $hidden-small-suffix : 'sm') {
    @media screen and (max-width: #{$hidden-medium-breakpoint}-1px) {
      .#{$hidden-prefix}-#{$hidden-small-suffix} {
        display: none !important;
      }
    }
}
```
When compiled with scssphp it evaluates wrong as:
```
@media screen and (max-width: 768px-1px) {
  .hidden-sm {
    display: none !important;
  }
}
```
When the correct form may be:
```
@media screen and (max-width: 767px) {
  .hidden-sm {
    display: none !important;
  }
}
```
Are there some way to avoid this? or is this an issue of scssphp?

**Comment by robocoder** [comment]
It's a problem with your scss. I'm pretty sure it won't work with Ruby sass either.

You probably want to change `#{$hidden-medium-breakpoint}-1px` to `($hidden-medium-breakpoint)-1px`.

**Comment by informas** [comment]
Hi Robocoder, thank you!
that you said is the solution for me.
When I made this change the compiled statement is correct, now.

But, all the .scss package that I have to compile, refers variables as #{$varname}. Must be I changes all to ($varname)?

Thanks in advance.
Jorge Colaccini

**Comment by robocoder** [comment]
No, you wouldn't change them all to `($varname)`.  The `#{$varname}` syntax is described here:
* http://sass-lang.com/documentation/file.SASS_REFERENCE.html#Interpolation_____

The reason I put parentheses is because you were expecting to perform an arithmetic operation but your varname was ambiguous. Specifically, sass allows varnames to contain numbers and hyphens, so scssphp thought the varname was `hidden-medium-breakpoint-1px`.

**Comment by informas** [comment]
Thanks you about your explanation.
Best regards.
Jorge Colaccini
