### ISSUE TITLE
Dollar prefix in SASS variables not required

### ISSUE THREAD

**Issue by JMitnik** [leafo/scssphp#588]
When compiling for example `foo: bar;`, the compiler is supposed to state something like "Invalid CSS after "foo: bar": expected "{", was "" ".

Instead, the compiler gives no error, and does not notice that there is a $dollar sign missing as a prefix for the variable. This should probably be fixed, unless I am missing something?

**Comment by niaccurshi** [comment]
I'm not sure that it should state this? Without a dollar sign the expectation should surely be that it's a property and value? Just because you are using "foo" without the dollar sign and that would appear to not be a current valid CSS property, it doesn't mean that it couldn't be. SCSS is agnostic to possible CSS properties after all!

**Comment by robocoder** [comment]
Yes, in this case, the parser should check it's inside a block. That said, the focus has been on compiling valid scss...

**Comment by niaccurshi** [comment]
I took a view at this and updated code as part of the pull request in #593
